export const SOURCES = [
  {
    id: "S1",
    title: "SECI / GRIDCO standalone BESS RfS",
    url: "https://www.seci.co.in/uploads/tenders/RfS-BESS_Projects-GRIDCO.pdf",
    note: "18 Dec 2025 · clauses 8.1(b), 8.1(c), pp. 17–20: AC metering-point dispatchable capacity, 420 annual operational cycles, 75% / 70% at years 10 / 12. Actual tender is in Odisha; Gujarat is our hypothetical reference climate.",
  },
  {
    id: "S2",
    title: "IMD Ahmedabad climatological table",
    url: "https://city.imd.gov.in/citywx/extreme/JUN/ahmedabad2.htm",
    note: "1991–2020 normal daily maxima and minima. Daily-mean array supplied by the team as an IMD-based approximation. This page reports August maximum 32.2°C; specified input is 32.3°C. The model preserves the supplied array; August is outside the outage stress months.",
  },
  {
    id: "S3",
    title: "EVE MB31 314 Ah product specification",
    url: "https://www.gobelpower.com/download/EVE-314Ah-CB31-LiFePO4-Cell-Datasheet.pdf",
    note: "Manufacturer-authored document hosted by a distributor. Cycle-life endpoint: 8,000 cycles to 70% SoH at 25°C ambient; test protocol includes rest periods and clamping. Calendar/cycle decomposition is assumed, not a validated MB31 model.",
  },
  {
    id: "S4",
    title: "BLAST-Lite — National Laboratory of the Rockies",
    url: "https://github.com/NatLabRockies/BLAST-Lite",
    note: "Public aging-model families and explicit cell-to-pack / extrapolation caveats. This demo does not execute BLAST-Lite or claim its validation.",
  },
  {
    id: "S5",
    title: "Naumann et al., 2018 · LFP calendar aging",
    url: "https://doi.org/10.1016/j.est.2018.01.019",
    note: "29-month study of Sony/Murata LFP/graphite cells; temperature- and SOC-dependent semi-empirical modeling. Supports the modeling approach, not the exact coefficients assumed here.",
  },
  {
    id: "S6",
    title: "Wang et al., 2011 · graphite–LiFePO₄ cycle life",
    url: "https://doi.org/10.1016/j.jpowsour.2010.11.134",
    note: "Reported temperature-sensitive cycle-life model. Cell, C-rate, and model formulation differ from this illustration; its coefficients are not universal.",
  },
  {
    id: "S7",
    title: "Large-format Li-ion degradation models",
    url: "https://github.com/NatLabRockies/BLAST-Lite",
    note: "BLAST-Lite includes large-format LFP modeling with chemistry- and usage-specific behavior. Low heat-sensitivity is presented as an uncertainty stress test, not a universal conclusion.",
  },
  {
    id: "S8",
    title: "BloombergNEF · 2025 battery pack price survey",
    url: "https://about.bnef.com/insights/clean-transport/lithium-ion-battery-pack-prices-fall-to-108-per-kilowatt-hour-despite-rising-metal-prices-bloombergnef/",
    note: "9 Dec 2025: stationary storage pack average $70/kWh. Pack prices are not delivered Indian augmentation or turnkey project costs.",
  },
  {
    id: "S9",
    title: "Munich Re · performance insurance launch",
    url: "https://www.munichre.com/en/company/media-relations/media-information-and-corporate-news/media-information/2019/2019-03-07-media-information.html",
    note: "7 Mar 2019; first customer ESS Inc., a flow-battery manufacturer. Establishes prior art for battery-performance insurance.",
  },
  {
    id: "S10",
    title: "TWAICE / Munich Re partnership",
    url: "https://www.twaice.com/newsroom/munich-re-partnership",
    note: "13 May 2020; battery monitoring and analytics supported lithium-ion performance warranty insurance.",
  },
  {
    id: "S11",
    title: "Hithium / Munich Re warranty reinsurance",
    url: "https://www.businesswire.com/news/home/20231026035229/en/Battery-Manufacturer-Hithium-to-Be-Reinsured-by-Munich-Re",
    note: "2023 company announcement: product and performance warranties covered for up to 15 years.",
  },
];
export const ASSUMPTIONS = [
  [
    "Reference project",
    "125 MW / 500 MWh",
    "Size input: 1–10,000 MWh",
    "Hypothetical Gujarat reference; scale inspired by S1",
    "ASSUMPTION",
  ],
  [
    "Year-10 / year-12 thresholds",
    "75% / 70%",
    "Year-10 input: 60–85%",
    "S1, pp. 19–20",
    "SOURCED",
  ],
  [
    "Contract annual cycle limit",
    "420/year",
    "1–2 operational cycles/day in tender",
    "S1, p. 17; model uses an EFC proxy",
    "SOURCED + PROXY",
  ],
  [
    "Ambient temperature",
    "12 repeated monthly normals",
    "Persistent site offset σ = 1°C",
    "Team-specified IMD-based means; S2",
    "APPROXIMATION",
  ],
  [
    "HVAC setpoint / solar gain",
    "25°C / +3°C",
    "Solar-gain sensitivity proposal: 0–5°C",
    "Simplified thermal exposure model",
    "ASSUMPTION",
  ],
  [
    "Self-heating proxy",
    "2°C per average cycle/day",
    "Sensitivity proposal: 0–4°C",
    "Does not model instantaneous C-rate or cooling power",
    "ASSUMPTION",
  ],
  [
    "Ambient coupling β",
    "0.15 / 0.40 / 0.70",
    "0–1; project σ = 0.05, clipped",
    "Best / Base / Worst, not a measured HVAC efficiency",
    "ASSUMPTION",
  ],
  [
    "Average cycling",
    "0.90 / 1.00 / 1.15",
    "Project σ = 10%; cap = 420/365",
    "Reduced realized throughput may be below availability obligations",
    "ASSUMPTION",
  ],
  [
    "High-charge resting factor",
    "1.00 / 1.10 / 1.25",
    "1.00–1.25",
    "Multiplier of calendar stress-time",
    "ASSUMPTION",
  ],
  [
    "Calendar coefficient",
    "1.8% / √year",
    "Sensitivity: 1.2–2.4%; log σ = 0.15",
    "S4–S5 motivate model family, not this fitted value",
    "ASSUMPTION",
  ],
  [
    "Calendar activation energy",
    "50 kJ/mol",
    "Project σ = 7 kJ/mol; test 40–60",
    "Activation of stress-time accumulation, inside √τ",
    "ASSUMPTION",
  ],
  [
    "Cycle activation energy",
    "30 kJ/mol",
    "Project σ = 6 kJ/mol; test 0–40",
    "S6–S7 motivate uncertainty; 0 sets heat effect to exactly zero",
    "ASSUMPTION",
  ],
  [
    "Cycle calibration",
    "8,000 cycles to 70%",
    "Sensitivity: 6,000–10,000",
    "S3 endpoint; assumed 4.4-year calendar contribution",
    "SOURCED + ASSUMPTION",
  ],
  [
    "Cycle-fade coefficient",
    "(0.30 − 0.018√4.4)/8,000",
    "Log σ = 0.15",
    "Assumed calendar/cycle decomposition",
    "ASSUMPTION",
  ],
  [
    "Cooling outages",
    "0 days baseline",
    "0–30 days/year, Apr–Jun",
    "Mean daily maximum sustained on outage days is a stress proxy",
    "ASSUMPTION",
  ],
  [
    "Installed augmentation cost",
    "₹1.0 crore/MWh",
    "Sensitivity proposal: ₹0.7–1.3 crore/MWh",
    "DC block + integration; S8 is context, not an installed quote",
    "ASSUMPTION",
  ],
  [
    "Annual cost decline",
    "4%",
    "Sensitivity: 0–6%",
    "Constant nominal-price trajectory",
    "ASSUMPTION",
  ],
  [
    "Discount rate",
    "10%",
    "Sensitivity: 8–12%",
    "Assumed nominal rate, paired with nominal future costs",
    "ASSUMPTION",
  ],
  [
    "Risk/admin/capital loading",
    "1.30×",
    "Sensitivity: 1.10–1.50×",
    "Illustrative loading; no demonstrated capital adequacy",
    "ASSUMPTION",
  ],
  [
    "Project capex",
    "₹1.6 crore/MWh",
    "Sensitivity proposal: ₹1.3–1.9 crore/MWh",
    "₹800 crore for reference project; not a supplier quotation",
    "ASSUMPTION",
  ],
  [
    "Scenario mixture",
    "25 / 50 / 25%",
    "Weights sum to 100%; not empirical frequencies",
    "Illustrative uncertainty mixture",
    "ASSUMPTION",
  ],
  [
    "Simulations and random seed",
    "2,000 / 42",
    "QA uses 10,000 with same seed",
    "Mulberry32 + Box–Muller; independent parameter draws, persistent per project",
    "MODEL SETTING",
  ],
];
